2024-02-15 09:16:20 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/Dr_Rosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/Dr_Rosa'
2024-02-15 09:16:20 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/Dr_Rosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/Dr_Rosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-15 09:26:33 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/'
2024-02-15 09:26:33 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-15 09:37:13 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-15 09:37:13 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-15 09:37:38 [ERROR]: ENOENT: no such file or directory, scandir '/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/Escritorio/Datos/DrRosa'
2024-02-15 09:37:38 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-15 09:41:00 [ERROR]: ENOENT: no such file or directory, scandir 'home/claudi/Escritorio/Datos/DrRosa/'
Error: ENOENT: no such file or directory, scandir 'home/claudi/Escritorio/Datos/DrRosa/'
2024-02-15 09:41:00 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir 'home/claudi/Escritorio/Datos/DrRosa/'
Error: Error: ENOENT: no such file or directory, scandir 'home/claudi/Escritorio/Datos/DrRosa/'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-15 09:41:52 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
2024-02-15 09:41:52 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-15 09:51:51 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
2024-02-15 09:51:51 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-15 15:03:38 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
2024-02-15 15:03:38 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa/'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-15 15:03:54 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-15 15:03:54 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-16 06:53:04 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-16 06:53:04 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-16 18:17:51 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos'
2024-02-16 18:17:51 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 08:57:42 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio'
2024-02-20 08:57:42 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 08:59:30 [ERROR]: ENOENT: no such file or directory, scandir '/root/Desktop'
Error: ENOENT: no such file or directory, scandir '/root/Desktop'
2024-02-20 08:59:30 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/root/Desktop'
Error: Error: ENOENT: no such file or directory, scandir '/root/Desktop'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:11:34 [ERROR]: PineconeAuthorizationError: The API key you provided was rejected while calling https://claudi-ucjo21o.svc.gcp-starter.pinecone.io/vectors/upsert. Please check your configuration values and try again. You can find the configuration values for your project in the Pinecone developer console at https://app.pinecone.io
Error: PineconeAuthorizationError: The API key you provided was rejected while calling https://claudi-ucjo21o.svc.gcp-starter.pinecone.io/vectors/upsert. Please check your configuration values and try again. You can find the configuration values for your project in the Pinecone developer console at https://app.pinecone.io
    at Pinecone_VectorStores.upsert (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Pinecone/Pinecone.js:40:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:273:17)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:11:34 [ERROR]: [server]: Error: Error: PineconeAuthorizationError: The API key you provided was rejected while calling https://claudi-ucjo21o.svc.gcp-starter.pinecone.io/vectors/upsert. Please check your configuration values and try again. You can find the configuration values for your project in the Pinecone developer console at https://app.pinecone.io
Error: Error: PineconeAuthorizationError: The API key you provided was rejected while calling https://claudi-ucjo21o.svc.gcp-starter.pinecone.io/vectors/upsert. Please check your configuration values and try again. You can find the configuration values for your project in the Pinecone developer console at https://app.pinecone.io
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:14:29 [ERROR]: PineconeAuthorizationError: The API key you provided was rejected while calling https://claudi-ucjo21o.svc.gcp-starter.pinecone.io/vectors/upsert. Please check your configuration values and try again. You can find the configuration values for your project in the Pinecone developer console at https://app.pinecone.io
Error: PineconeAuthorizationError: The API key you provided was rejected while calling https://claudi-ucjo21o.svc.gcp-starter.pinecone.io/vectors/upsert. Please check your configuration values and try again. You can find the configuration values for your project in the Pinecone developer console at https://app.pinecone.io
    at Pinecone_VectorStores.upsert (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Pinecone/Pinecone.js:40:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:273:17)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:14:29 [ERROR]: [server]: Error: Error: PineconeAuthorizationError: The API key you provided was rejected while calling https://claudi-ucjo21o.svc.gcp-starter.pinecone.io/vectors/upsert. Please check your configuration values and try again. You can find the configuration values for your project in the Pinecone developer console at https://app.pinecone.io
Error: Error: PineconeAuthorizationError: The API key you provided was rejected while calling https://claudi-ucjo21o.svc.gcp-starter.pinecone.io/vectors/upsert. Please check your configuration values and try again. You can find the configuration values for your project in the Pinecone developer console at https://app.pinecone.io
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:16:50 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-20 09:16:50 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:17:21 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-20 09:17:21 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:17:35 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-20 09:17:35 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:18:46 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-20 09:18:46 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:21:23 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-20 09:21:23 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 09:21:30 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-20 09:21:30 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:22:00 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-20 09:22:00 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:23:04 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-20 09:23:04 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:23:25 [ERROR]: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
2024-02-20 09:23:25 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
Error: Error: ENOENT: no such file or directory, scandir '/home/claudi/Escritorio/Datos/DrRosa'
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1345:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1017:13
2024-02-20 09:47:32 [ERROR]: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at _coerceToRunnable (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1265:15)
    at Array.map (<anonymous>)
    at RunnableSequence.from (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:942:44)
    at createRetrieverChain (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:209:63)
    at createChain (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:246:28)
    at ConversationalRetrievalQAChain_Chains.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:124:29)
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:289:58)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 09:47:32 [ERROR]: [server]: Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 09:47:48 [ERROR]: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at _coerceToRunnable (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1265:15)
    at Array.map (<anonymous>)
    at RunnableSequence.from (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:942:44)
    at createRetrieverChain (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:209:63)
    at createChain (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:246:28)
    at ConversationalRetrievalQAChain_Chains.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:124:29)
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:289:58)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 09:47:48 [ERROR]: [server]: Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 09:47:54 [ERROR]: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at _coerceToRunnable (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1265:15)
    at Array.map (<anonymous>)
    at RunnableSequence.from (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:942:44)
    at createRetrieverChain (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:209:63)
    at createChain (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:246:28)
    at ConversationalRetrievalQAChain_Chains.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:124:29)
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:289:58)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 09:47:54 [ERROR]: [server]: Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 09:48:26 [ERROR]: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at _coerceToRunnable (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1265:15)
    at Array.map (<anonymous>)
    at RunnableSequence.from (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:942:44)
    at createRetrieverChain (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:209:63)
    at createChain (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:246:28)
    at ConversationalRetrievalQAChain_Chains.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:124:29)
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:289:58)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 09:48:26 [ERROR]: [server]: Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 09:48:41 [ERROR]: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at _coerceToRunnable (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1265:15)
    at Array.map (<anonymous>)
    at RunnableSequence.from (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:942:44)
    at createRetrieverChain (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:209:63)
    at createChain (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:246:28)
    at ConversationalRetrievalQAChain_Chains.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:124:29)
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:289:58)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 09:48:41 [ERROR]: [server]: Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1502:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 10:45:00 [ERROR]: [server]: Error: The model HiTZ/latxa-7b-v1 is too large to be loaded automatically (13GB > 10GB). Please use Spaces (https://huggingface.co/spaces) or Inference Endpoints (https://huggingface.co/inference-endpoints).
Error: The model HiTZ/latxa-7b-v1 is too large to be loaded automatically (13GB > 10GB). Please use Spaces (https://huggingface.co/spaces) or Inference Endpoints (https://huggingface.co/inference-endpoints).
    at request (/usr/local/lib/node_modules/flowise/node_modules/@huggingface/inference/dist/index.js:215:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async textGeneration (/usr/local/lib/node_modules/flowise/node_modules/@huggingface/inference/dist/index.js:713:15)
    at async RetryOperation._fn (/usr/local/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12)
2024-02-20 10:45:59 [ERROR]: [server]: Error: The model HiTZ/latxa-7b-v1 is too large to be loaded automatically (13GB > 10GB). Please use Spaces (https://huggingface.co/spaces) or Inference Endpoints (https://huggingface.co/inference-endpoints).
Error: The model HiTZ/latxa-7b-v1 is too large to be loaded automatically (13GB > 10GB). Please use Spaces (https://huggingface.co/spaces) or Inference Endpoints (https://huggingface.co/inference-endpoints).
    at request (/usr/local/lib/node_modules/flowise/node_modules/@huggingface/inference/dist/index.js:215:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async textGeneration (/usr/local/lib/node_modules/flowise/node_modules/@huggingface/inference/dist/index.js:713:15)
    at async RetryOperation._fn (/usr/local/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12)
2024-02-20 14:54:46 [ERROR]: [server]: Error: Error: Error processing thread: failed, Thread ID: thread_jnKW7ChsZtpJn6yIGyzwI7wA, Run ID: run_0wAtuSNoYg7yfJ6JValMFefO, Status: failed
Error: Error: Error processing thread: failed, Thread ID: thread_jnKW7ChsZtpJn6yIGyzwI7wA, Run ID: run_0wAtuSNoYg7yfJ6JValMFefO, Status: failed
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:460:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1531:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 14:55:07 [ERROR]: [server]: Error: Error: Error processing thread: failed, Thread ID: thread_jnKW7ChsZtpJn6yIGyzwI7wA, Run ID: run_JJ2BDII8Do7TMIq4BsewU6Lp, Status: failed
Error: Error: Error processing thread: failed, Thread ID: thread_jnKW7ChsZtpJn6yIGyzwI7wA, Run ID: run_JJ2BDII8Do7TMIq4BsewU6Lp, Status: failed
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:460:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1531:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 14:57:03 [ERROR]: [server]: Error: Error: Error submitting tool outputs: requires_action, Thread ID: thread_kK67Z6UdoP4IV0rsAK31yPcm, Run ID: run_SvJzG0l6RO6nI77lgw1ETNuR
Error: Error: Error submitting tool outputs: requires_action, Thread ID: thread_kK67Z6UdoP4IV0rsAK31yPcm, Run ID: run_SvJzG0l6RO6nI77lgw1ETNuR
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:460:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1531:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 16:33:36 [ERROR]: [server]: Error: Error: Error processing thread: failed, Thread ID: thread_VCac7gz6OwG1lDM8XlQvencF, Run ID: run_7OPAxoAihkvLiofxYYYSXfej, Status: failed
Error: Error: Error processing thread: failed, Thread ID: thread_VCac7gz6OwG1lDM8XlQvencF, Run ID: run_7OPAxoAihkvLiofxYYYSXfej, Status: failed
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:460:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1531:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 16:52:39 [ERROR]: [server]: Error: Error: 404 No thread found with id 'thread_YTeUzjHhzInZbqOxzu80grsU'.
Error: Error: 404 No thread found with id 'thread_YTeUzjHhzInZbqOxzu80grsU'.
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:460:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1531:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 16:52:58 [ERROR]: [server]: Error: Error: 404 No thread found with id 'thread_YTeUzjHhzInZbqOxzu80grsU'.
Error: Error: 404 No thread found with id 'thread_YTeUzjHhzInZbqOxzu80grsU'.
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:460:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1531:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 16:54:03 [ERROR]: [server]: Error: Error: 404 No thread found with id 'thread_YTeUzjHhzInZbqOxzu80grsU'.
Error: Error: 404 No thread found with id 'thread_YTeUzjHhzInZbqOxzu80grsU'.
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:460:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1531:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-20 16:54:22 [ERROR]: [server]: Error: Error: 404 No thread found with id 'thread_YTeUzjHhzInZbqOxzu80grsU'.
Error: Error: 404 No thread found with id 'thread_YTeUzjHhzInZbqOxzu80grsU'.
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:460:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1531:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
2024-02-23 10:26:50 [ERROR]: ❌ [server]: Error during Data Source initialization: connect ECONNREFUSED 127.0.0.1:3306
Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
    --------------------
    at Protocol._enqueue (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Pool.js:48:16)
    at /usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlDriver.js:1012:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlDriver.js:1009:16)
    at MysqlDriver.connect (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlDriver.js:305:36)
    at DataSource.initialize (/usr/local/lib/node_modules/flowise/node_modules/typeorm/data-source/DataSource.js:136:27)
    at App.initDatabase (/usr/local/lib/node_modules/flowise/dist/index.js:71:28)
2024-02-23 10:39:52 [ERROR]: ❌[server]: Flowise Server shut down error: TypeError: Cannot read properties of undefined (reading 'flush')
2024-02-23 10:39:58 [ERROR]: ❌ [server]: Error during Data Source initialization: connect ECONNREFUSED 127.0.0.1:3306
Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
    --------------------
    at Protocol._enqueue (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Pool.js:48:16)
    at /usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlDriver.js:1012:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlDriver.js:1009:16)
    at MysqlDriver.connect (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlDriver.js:305:36)
    at DataSource.initialize (/usr/local/lib/node_modules/flowise/node_modules/typeorm/data-source/DataSource.js:136:27)
    at App.initDatabase (/usr/local/lib/node_modules/flowise/dist/index.js:71:28)
2024-02-23 10:41:57 [ERROR]: ❌[server]: Flowise Server shut down error: TypeError: Cannot read properties of undefined (reading 'flush')
2024-02-23 10:42:04 [ERROR]: ❌ [server]: Error during Data Source initialization: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
QueryFailedError: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-02-23 10:47:25 [ERROR]: ❌[server]: Flowise Server shut down error: TypeError: Cannot read properties of undefined (reading 'flush')
2024-02-23 17:56:30 [ERROR]: [server]: Error: API key must be provided when using hosted LangSmith API
Error: API key must be provided when using hosted LangSmith API
    at Client.validateApiKeyIfHosted (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:138:19)
    at new Client (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:121:14)
    at RunTree.getDefaultConfig (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:166:21)
    at new RunTree (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:147:39)
    at AnalyticHandler.onChainStart (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:326:35)
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:185:50)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1541:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1066:13
2024-02-23 17:56:56 [ERROR]: [server]: Error: API key must be provided when using hosted LangSmith API
Error: API key must be provided when using hosted LangSmith API
    at Client.validateApiKeyIfHosted (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:138:19)
    at new Client (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:121:14)
    at RunTree.getDefaultConfig (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:166:21)
    at new RunTree (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:147:39)
    at AnalyticHandler.onChainStart (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:326:35)
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:185:50)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1541:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1066:13
2024-02-23 17:57:05 [ERROR]: [server]: Error: API key must be provided when using hosted LangSmith API
Error: API key must be provided when using hosted LangSmith API
    at Client.validateApiKeyIfHosted (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:138:19)
    at new Client (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:121:14)
    at RunTree.getDefaultConfig (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:166:21)
    at new RunTree (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:147:39)
    at AnalyticHandler.onChainStart (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:326:35)
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:185:50)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1541:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1066:13
2024-02-23 17:57:42 [ERROR]: [server]: Error: API key must be provided when using hosted LangSmith API
Error: API key must be provided when using hosted LangSmith API
    at Client.validateApiKeyIfHosted (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:138:19)
    at new Client (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:121:14)
    at RunTree.getDefaultConfig (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:166:21)
    at new RunTree (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:147:39)
    at AnalyticHandler.onChainStart (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:326:35)
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:185:50)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1541:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1066:13
2024-02-23 17:58:56 [ERROR]: [server]: Error: API key must be provided when using hosted LangSmith API
Error: API key must be provided when using hosted LangSmith API
    at Client.validateApiKeyIfHosted (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:138:19)
    at new Client (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:121:14)
    at RunTree.getDefaultConfig (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:166:21)
    at new RunTree (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:147:39)
    at AnalyticHandler.onChainStart (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:326:35)
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:185:50)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1541:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1066:13
2024-02-23 18:05:55 [ERROR]: [server]: Error: API key must be provided when using hosted LangSmith API
Error: API key must be provided when using hosted LangSmith API
    at Client.validateApiKeyIfHosted (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:138:19)
    at new Client (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/client.cjs:121:14)
    at RunTree.getDefaultConfig (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:166:21)
    at new RunTree (/usr/local/lib/node_modules/flowise/node_modules/langsmith/dist/run_trees.cjs:147:39)
    at AnalyticHandler.onChainStart (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:326:35)
    at OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:185:50)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1541:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1066:13
2024-03-01 16:13:25 [ERROR]: Error: Credentials could not be decrypted.
Error: Error: Credentials could not be decrypted.
    at getCredentialData (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/utils.js:537:15)
    at async ChatOpenAI_ChatModels.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chatmodels/ChatOpenAI/ChatOpenAI.js:206:32)
    at async buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:290:36)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1708:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1152:13
2024-03-01 16:13:25 [ERROR]: [server]: Error: Error: Error: Credentials could not be decrypted.
Error: Error: Error: Credentials could not be decrypted.
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:333:19)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1708:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1152:13
2024-03-01 16:13:47 [ERROR]: Error: Credentials could not be decrypted.
Error: Error: Credentials could not be decrypted.
    at getCredentialData (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/utils.js:537:15)
    at async ChatOpenAI_ChatModels.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chatmodels/ChatOpenAI/ChatOpenAI.js:206:32)
    at async buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:290:36)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1708:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1152:13
2024-03-01 16:13:47 [ERROR]: [server]: Error: Error: Error: Credentials could not be decrypted.
Error: Error: Error: Credentials could not be decrypted.
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:333:19)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1708:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1152:13
2024-03-01 16:14:46 [ERROR]: Error: Credentials could not be decrypted.
Error: Error: Credentials could not be decrypted.
    at getCredentialData (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/utils.js:537:15)
    at async ChatOpenAI_ChatModels.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chatmodels/ChatOpenAI/ChatOpenAI.js:206:32)
    at async buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:290:36)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1708:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1152:13
2024-03-01 16:14:46 [ERROR]: [server]: Error: Error: Error: Credentials could not be decrypted.
Error: Error: Error: Credentials could not be decrypted.
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:333:19)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1708:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1152:13
2024-03-01 16:15:11 [ERROR]: Error: Credentials could not be decrypted.
Error: Error: Credentials could not be decrypted.
    at getCredentialData (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/utils.js:537:15)
    at async ChatOpenAI_ChatModels.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chatmodels/ChatOpenAI/ChatOpenAI.js:206:32)
    at async buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:290:36)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1708:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1152:13
2024-03-01 16:15:11 [ERROR]: [server]: Error: Error: Error: Credentials could not be decrypted.
Error: Error: Error: Credentials could not be decrypted.
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:333:19)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1708:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1152:13
2024-03-01 16:15:28 [ERROR]: [server]: Error: Error: Credentials could not be decrypted.
Error: Error: Credentials could not be decrypted.
    at getCredentialData (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/utils.js:537:15)
    at async OpenAIAssistant_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/OpenAIAssistant/OpenAIAssistant.js:177:32)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1738:19)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1152:13
2024-03-01 17:11:42 [ERROR]: ❌ [server]: Error during Data Source initialization: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
QueryFailedError: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-03-01 17:14:04 [ERROR]: unhandledRejection: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
QueryFailedError: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
QueryFailedError: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-03-01 17:14:04 [ERROR]: unhandledRejection: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
QueryFailedError: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
QueryFailedError: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-03-01 17:14:04 [ERROR]: unhandledRejection:  ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
QueryFailedError: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-03-01 17:14:11 [ERROR]: ❌ [server]: Error during Data Source initialization: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
QueryFailedError: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-03-01 17:14:14 [ERROR]: unhandledRejection: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
QueryFailedError: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
QueryFailedError: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-03-01 17:14:14 [ERROR]: unhandledRejection: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
QueryFailedError: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
QueryFailedError: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-03-01 17:14:14 [ERROR]: unhandledRejection:  ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
QueryFailedError: ER_NO_SUCH_TABLE: Table 'flowise.chat_flow' doesn't exist
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-03-01 17:14:22 [ERROR]: ❌ [server]: Error during Data Source initialization: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
QueryFailedError: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-03-01 17:14:26 [ERROR]: unhandledRejection: Cannot read properties of undefined (reading 'componentCredentials')
TypeError: Cannot read properties of undefined (reading 'componentCredentials')
    at /usr/local/lib/node_modules/flowise/dist/index.js:181:51
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
    at authMiddleware (/usr/local/lib/node_modules/flowise/node_modules/express-basic-auth/index.js:64:16)
    at /usr/local/lib/node_modules/flowise/dist/index.js:150:83
TypeError: Cannot read properties of undefined (reading 'componentCredentials')
    at /usr/local/lib/node_modules/flowise/dist/index.js:181:51
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
    at authMiddleware (/usr/local/lib/node_modules/flowise/node_modules/express-basic-auth/index.js:64:16)
    at /usr/local/lib/node_modules/flowise/dist/index.js:150:83
2024-03-01 17:14:26 [ERROR]: unhandledRejection: Cannot read properties of undefined (reading 'componentCredentials')
TypeError: Cannot read properties of undefined (reading 'componentCredentials')
    at /usr/local/lib/node_modules/flowise/dist/index.js:181:51
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
    at authMiddleware (/usr/local/lib/node_modules/flowise/node_modules/express-basic-auth/index.js:64:16)
    at /usr/local/lib/node_modules/flowise/dist/index.js:150:83
TypeError: Cannot read properties of undefined (reading 'componentCredentials')
    at /usr/local/lib/node_modules/flowise/dist/index.js:181:51
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
    at authMiddleware (/usr/local/lib/node_modules/flowise/node_modules/express-basic-auth/index.js:64:16)
    at /usr/local/lib/node_modules/flowise/dist/index.js:150:83
2024-03-01 17:14:26 [ERROR]: unhandledRejection:  Cannot read properties of undefined (reading 'componentCredentials')
TypeError: Cannot read properties of undefined (reading 'componentCredentials')
    at /usr/local/lib/node_modules/flowise/dist/index.js:181:51
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
    at authMiddleware (/usr/local/lib/node_modules/flowise/node_modules/express-basic-auth/index.js:64:16)
    at /usr/local/lib/node_modules/flowise/dist/index.js:150:83
2024-03-01 17:14:33 [ERROR]: ❌ [server]: Error during Data Source initialization: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
QueryFailedError: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/mysql/lib/Connection.js:88:28)
2024-03-01 17:17:18 [ERROR]: ❌[server]: Flowise Server shut down error: TypeError: Cannot read properties of undefined (reading 'flush')
2024-03-01 17:54:49 [ERROR]: [server]: Error: 401 Incorrect API key provided: sk-nLqQu***************************************Snrq. You can find your API key at https://platform.openai.com/account/api-keys.
Error: 401 Incorrect API key provided: sk-nLqQu***************************************Snrq. You can find your API key at https://platform.openai.com/account/api-keys.
    at APIError.generate (/usr/local/lib/node_modules/flowise/node_modules/openai/error.js:47:20)
    at OpenAI.makeStatusError (/usr/local/lib/node_modules/flowise/node_modules/openai/core.js:263:33)
    at OpenAI.makeRequest (/usr/local/lib/node_modules/flowise/node_modules/openai/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/openai/dist/chat_models.cjs:650:29
    at async RetryOperation._fn (/usr/local/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12)
2024-03-01 17:55:31 [ERROR]: [server]: Error: 401 Incorrect API key provided: sk-nLqQu***************************************Snrq. You can find your API key at https://platform.openai.com/account/api-keys.
Error: 401 Incorrect API key provided: sk-nLqQu***************************************Snrq. You can find your API key at https://platform.openai.com/account/api-keys.
    at APIError.generate (/usr/local/lib/node_modules/flowise/node_modules/openai/error.js:47:20)
    at OpenAI.makeStatusError (/usr/local/lib/node_modules/flowise/node_modules/openai/core.js:263:33)
    at OpenAI.makeRequest (/usr/local/lib/node_modules/flowise/node_modules/openai/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/openai/dist/chat_models.cjs:650:29
    at async RetryOperation._fn (/usr/local/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12)
2024-03-01 17:56:45 [ERROR]: unhandledRejection: Error: Error: Credentials could not be decrypted.
Error: Error: Error: Credentials could not be decrypted.
    at AnalyticHandler.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:304:19)
Error: Error: Error: Credentials could not be decrypted.
    at AnalyticHandler.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:304:19)
2024-03-01 17:56:45 [ERROR]: unhandledRejection: Error: Error: Credentials could not be decrypted.
Error: Error: Error: Credentials could not be decrypted.
    at AnalyticHandler.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:304:19)
Error: Error: Error: Credentials could not be decrypted.
    at AnalyticHandler.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:304:19)
2024-03-01 17:56:45 [ERROR]: unhandledRejection:  Error: Error: Credentials could not be decrypted.
Error: Error: Error: Credentials could not be decrypted.
    at AnalyticHandler.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/handler.js:304:19)
2024-03-01 17:57:11 [ERROR]: 401 Incorrect API key provided: sk-nLqQu***************************************Snrq. You can find your API key at https://platform.openai.com/account/api-keys.
Error: 401 Incorrect API key provided: sk-nLqQu***************************************Snrq. You can find your API key at https://platform.openai.com/account/api-keys.
    at APIError.generate (/usr/local/lib/node_modules/flowise/node_modules/openai/error.js:47:20)
    at OpenAI.makeStatusError (/usr/local/lib/node_modules/flowise/node_modules/openai/core.js:263:33)
    at OpenAI.makeRequest (/usr/local/lib/node_modules/flowise/node_modules/openai/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/openai/dist/chat_models.cjs:650:29
    at async RetryOperation._fn (/usr/local/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12)
2024-03-01 17:57:11 [ERROR]: [server]: Error: Error: 401 Incorrect API key provided: sk-nLqQu***************************************Snrq. You can find your API key at https://platform.openai.com/account/api-keys.
Error: Error: 401 Incorrect API key provided: sk-nLqQu***************************************Snrq. You can find your API key at https://platform.openai.com/account/api-keys.
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:333:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1708:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1152:13
2024-03-01 17:57:36 [ERROR]: [server]: Error: 401 Incorrect API key provided: sk-nLqQu***************************************Snrq. You can find your API key at https://platform.openai.com/account/api-keys.
Error: 401 Incorrect API key provided: sk-nLqQu***************************************Snrq. You can find your API key at https://platform.openai.com/account/api-keys.
    at APIError.generate (/usr/local/lib/node_modules/flowise/node_modules/openai/error.js:47:20)
    at OpenAI.makeStatusError (/usr/local/lib/node_modules/flowise/node_modules/openai/core.js:263:33)
    at OpenAI.makeRequest (/usr/local/lib/node_modules/flowise/node_modules/openai/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/openai/dist/chat_models.cjs:650:29
    at async RetryOperation._fn (/usr/local/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12)
